apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulsenet-api-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Shivam311201/pulsenet.git'
    path: kubernetes
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pulsenet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true