kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 30007
      hostPort: 30007
    - containerPort: 80
      hostPort: 8080
  - role: worker
    extraPortMappings:
    - containerPort: 30007
      hostPort: 30008
    - containerPort: 80
      hostPort: 8080
