apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: pulsenet
    tier: database
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: pulsenet
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsenet-mysql
  labels:
    app: pulsenet
    tier: database
spec:
  selector:
    matchLabels:
      app: pulsenet
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pulsenet
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pulsenet-api-secrets
              key: SPRING_DATASOURCE_PASSWORD
        - name: MYSQL_DATABASE
          value: pulsenet_db
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pulsenet-mysql
  labels:
    app: pulsenet
    tier: database
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: pulsenet
    tier: database